[package]
name = "rubato"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
askama = "0.14.0"
axum = { version = "0.8.7", features = ["multipart"] }
chrono = { version = "0.4.42", features = ["serde"] }
dotenvy = "0.15.7"
serde = { version = "1.0.228", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["chrono", "postgres", "runtime-tokio", "sqlite", "tls-native-tls"] }
tokio = { version = "1.48.0", features = ["full"] }
tower-http = { version = "0.6.8", features = ["fs", "trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
argon2 = "0.5.3"
rand = "0.8.5"
rpassword = "7.3.1"
axum-extra = { version = "0.10.0", features = ["cookie-signed"] }
jsonwebtoken = "9.2.0"
aws-config = "1.5.10"
aws-sdk-s3 = "1.65.0"
async-trait = "0.1.77"
infer = "0.15.0"
uuid = { version = "1.11.0", features = ["v4", "fast-rng", "macro-diagnostics"] }
tokio-util = "0.7.17"
serde_json = "1.0.148"
